# Generated by Django 3.0 on 2020-07-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smsimported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_id', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('message', models.CharField(max_length=200, verbose_name='Text Message')),
                ('datecreated', models.DateTimeField(verbose_name='Date Created')),
                ('datesent', models.DateTimeField(verbose_name='Date Sent')),
                ('sent', models.IntegerField(verbose_name='Is SMS sent')),
                ('attempt', models.IntegerField()),
                ('provider', models.IntegerField(verbose_name='Telco')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
            ],
        ),
    ]
