# Generated by Django 3.0 on 2020-07-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smsimported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_id', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=20)),
                ('datecreated', models.DateField()),
                ('datesent', models.DateField()),
                ('sent', models.IntegerField()),
                ('attempt', models.IntegerField()),
                ('provider', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
