# Generated by Django 3.0 on 2020-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smsdelivered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsimported_id', models.IntegerField(verbose_name='SMS ID')),
                ('messageid', models.CharField(max_length=200, verbose_name='Message ID')),
                ('mobilenumber', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('message', models.CharField(max_length=200, verbose_name='Text Message')),
                ('datesubmitted', models.DateTimeField(verbose_name='Date Created')),
                ('datedelivered', models.DateTimeField(blank=True, null=True, verbose_name='Date Sent')),
                ('delivered', models.IntegerField(verbose_name='Is SMS delivered')),
                ('msgstatus', models.CharField(blank=True, max_length=50, null=True, verbose_name='Message Status')),
                ('provider', models.IntegerField(verbose_name='Telco')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='smsimported',
            options={'verbose_name': 'SMS', 'verbose_name_plural': 'SMS'},
        ),
    ]
