# Generated by Django 3.0 on 2020-07-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_auto_20200725_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='media/')),
                ('datecreated', models.DateTimeField(verbose_name='Date Created')),
                ('user_id', models.IntegerField(verbose_name='User ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='smsdelivered',
            options={'verbose_name': 'SMS Delivered', 'verbose_name_plural': 'SMS Delivered'},
        ),
        migrations.AlterField(
            model_name='smsdelivered',
            name='datedelivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Delivered'),
        ),
        migrations.AlterField(
            model_name='smsdelivered',
            name='datesubmitted',
            field=models.DateTimeField(verbose_name='Date submitted'),
        ),
    ]
